"""Tests for pipeline/ui/manifest_io.py — the UI manifest CRUD helpers.

Covers:
  - Filename validation (NAME_RE)
  - YAML round trip (save → load_raw → save preserves shape)
  - validate_for_save() catches PHI without BAA, bad enums, missing fields
  - validate_path_warnings() flags non-existent source paths (non-blocking)
  - browse_listing() sandbox: paths outside BROWSE_ROOTS get redirected
  - Manifest schema actually loads what the UI writes
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest

from pipeline.core.manifest import Manifest
from pipeline.ui import manifest_io as mio


@pytest.fixture
def manifests_tmp(tmp_path, monkeypatch):
    """Point manifest_io at a tmp dir for isolated tests."""
    monkeypatch.setenv("AI_PROTECT_MANIFESTS_DIR", str(tmp_path))
    return tmp_path


def _minimal_data(**overrides) -> dict:
    base = dict(
        name="test-mfst",
        owner="o@example.com",
        on_call="o@example.com",
        description="t",
        data_sensitivity="confidential",
        decision_impact="advisory",
        integration_footprint="read_only",
        user_population="single_user",
        source_paths=["/tmp/some/place"],
        source_excludes=[],
    )
    base.update(overrides)
    return base


# ---- path_for / NAME_RE ----

def test_path_for_accepts_normal_name(manifests_tmp):
    p = mio.path_for("a-good-name_42")
    assert p.parent.resolve() == manifests_tmp.resolve()
    assert p.name == "a-good-name_42.yml"


@pytest.mark.parametrize("bad", [
    "Uppercase",
    "starts_with_underscore",   # actually allowed by regex... let me check
    "123starts-with-digit",
    "has spaces",
    "has/slash",
    "../escape",
    "",
    "a",  # too short — min 2 chars
])
def test_path_for_rejects_bad_names(manifests_tmp, bad):
    if bad == "starts_with_underscore":
        # regex actually allows underscores after first char; this is a confusion
        # not an error — explicitly demonstrate it's the first-char rule.
        with pytest.raises(ValueError):
            mio.path_for("_bad")
        return
    with pytest.raises(ValueError):
        mio.path_for(bad)


# ---- save / load_raw round trip ----

def test_save_then_load_round_trip(manifests_tmp):
    data = _minimal_data()
    p = mio.save("test-mfst", data, overwrite=False)
    assert p.is_file()
    text = p.read_text()
    assert text.startswith("# Generated by the ai-protect UI"), \
        "header comment must be present"

    loaded = mio.load_raw("test-mfst")
    # Same fields land back. on_call defaults from owner if blank — both set here.
    assert loaded["name"] == data["name"]
    assert loaded["owner"] == data["owner"]
    assert loaded["data_sensitivity"] == "confidential"
    assert loaded["source_paths"] == ["/tmp/some/place"]


def test_save_yaml_is_loadable_by_manifest_schema(manifests_tmp):
    """The YAML the UI writes must be loadable by the Manifest dataclass."""
    data = _minimal_data(
        name="schema-roundtrip",
        source_paths=["/a", "/b"],
        source_excludes=["__pycache__", "*.pyc"],
    )
    mio.save("schema-roundtrip", data)
    p = mio.path_for("schema-roundtrip")
    m = Manifest.from_yaml(p)
    assert m.name == "schema-roundtrip"
    assert m.scan_targets() == ["/a", "/b"]
    assert m.is_excluded("/foo/bar.pyc") is True


def test_save_refuses_overwrite_by_default(manifests_tmp):
    mio.save("dup", _minimal_data(name="dup"), overwrite=False)
    with pytest.raises(FileExistsError):
        mio.save("dup", _minimal_data(name="dup"), overwrite=False)


def test_save_allows_overwrite_when_requested(manifests_tmp):
    mio.save("overwrite", _minimal_data(name="overwrite", description="v1"))
    mio.save("overwrite",
             _minimal_data(name="overwrite", description="v2"),
             overwrite=True)
    assert mio.load_raw("overwrite")["description"] == "v2"


# ---- validation ----

class TestValidateForSave:
    def test_minimal_valid(self):
        assert mio.validate_for_save(_minimal_data()) == []

    def test_missing_required_fields(self):
        errs = mio.validate_for_save({"name": "foo"})
        # owner, data_sensitivity, decision_impact, integration_footprint, user_population all missing
        assert len(errs) >= 5

    def test_bad_enum_value(self):
        errs = mio.validate_for_save(
            _minimal_data(data_sensitivity="nuclear-launch-codes"))
        assert any("data_sensitivity" in e for e in errs)

    def test_phi_without_baa_blocked(self):
        """The Manifest.validate() policy gate fires — PHI sent to a non-BAA
        model isn't allowed."""
        data = _minimal_data(
            data_sensitivity="phi",
            decision_impact="clinical_influence",
            models=[{
                "name": "test-model",
                "provider": "openai",
                "model": "gpt-4",
                "via_gateway": True,
                "baa_covered": False,
            }],
        )
        errs = mio.validate_for_save(data)
        assert any("BAA" in e or "baa_covered" in e for e in errs)

    def test_bad_name_format(self):
        errs = mio.validate_for_save(_minimal_data(name="Bad Name With Spaces"))
        assert any("name must match" in e for e in errs)

    def test_source_paths_must_be_list(self):
        errs = mio.validate_for_save(_minimal_data(source_paths="just a string"))
        assert any("source_paths must be a list" in e for e in errs)


def test_path_warnings_are_non_blocking(manifests_tmp):
    """Non-existent source paths produce warnings, not errors."""
    data = _minimal_data(source_paths=["/definitely/does/not/exist"])
    # validation passes (warnings are separate)
    assert mio.validate_for_save(data) == []
    warns = mio.validate_path_warnings(data)
    assert len(warns) == 1
    assert "does not exist" in warns[0]


# ---- delete ----

def test_delete_removes_file(manifests_tmp):
    mio.save("doomed", _minimal_data(name="doomed"))
    p = mio.path_for("doomed")
    assert p.is_file()
    mio.delete("doomed")
    assert not p.exists()


def test_delete_missing_raises(manifests_tmp):
    with pytest.raises(FileNotFoundError):
        mio.delete("never-existed")


def test_list_existing_names(manifests_tmp):
    mio.save("alpha", _minimal_data(name="alpha"))
    mio.save("beta", _minimal_data(name="beta"))
    names = mio.list_existing_names()
    assert "alpha" in names and "beta" in names


# ---- browse_listing sandbox ----

def test_browse_listing_inside_sandbox():
    """Inside HOME is allowed."""
    d = mio.browse_listing(os.path.expanduser("~"))
    assert d.get("can_use") is True
    assert d.get("path") == os.path.expanduser("~")
    assert isinstance(d.get("dirs"), list)


def test_browse_listing_outside_sandbox_redirects():
    """Paths outside BROWSE_ROOTS get bounced to HOME, not 404."""
    d = mio.browse_listing("/etc")  # not in BROWSE_ROOTS
    assert d.get("path") == os.path.expanduser("~")


def test_browse_listing_non_existent_path():
    """Non-existent path under HOME (still in sandbox) returns error gracefully."""
    d = mio.browse_listing("/home/user/does/not/exist/anywhere")
    assert d.get("can_use") is False or d.get("error") is not None
