"""Generate unit tests from a Proposal.test_plan.

Each plan kind has a generator that returns (test_name, test_path, source).
The engine writes the file, runs pytest pre-apply (expect FAIL — bug present),
applies the patch, runs pytest again (expect PASS — bug fixed). On generator
failure or when no plan applies, the engine records `no_test_possible`.
"""
from __future__ import annotations

import os
import textwrap
import time
from pathlib import Path
from typing import Any

from .state import REMEDIATE_HOME

TESTS_ROOT = REMEDIATE_HOME / "tests"


def author_tests(change_id: str, plan: dict[str, Any]) -> list[tuple[str, str, str]]:
    """Return list of (test_name, abs_path, source). [] if not generatable."""
    if not plan:
        return []
    kind = plan.get("kind")
    if kind == "pin_version":
        return [_author_pin_version(change_id, plan)]
    if kind == "http_header":
        return [_author_http_header(change_id, plan)]
    return []


def _author_pin_version(change_id: str, plan: dict) -> tuple[str, str, str]:
    pkg = plan["package"]
    min_version = plan.get("min_version") or ""
    req_path = plan["requirements_path"]
    name = f"test_pin_{pkg.replace('-', '_').replace('.', '_')}"
    test_dir = TESTS_ROOT / change_id
    test_dir.mkdir(parents=True, exist_ok=True)
    test_path = test_dir / f"{name}.py"
    src = textwrap.dedent(f'''
        """Auto-generated by ai-protect: validates that {pkg} is pinned to a
        version that clears the originating finding."""
        import re
        from pathlib import Path

        REQ_PATH = Path({req_path!r})
        PKG = {pkg!r}
        MIN = {min_version!r}


        def _parse_pin(line: str):
            m = re.match(r"^([A-Za-z0-9_.\\-]+)\\s*==\\s*([^\\s#]+)", line.strip())
            if m:
                return m.group(1), m.group(2)
            return None, None


        def _ver_key(v: str):
            parts = []
            cur = ""
            for ch in v:
                if ch.isdigit():
                    cur += ch
                else:
                    if cur:
                        parts.append(int(cur))
                        cur = ""
                    parts.append(ch)
            if cur:
                parts.append(int(cur))
            return tuple(parts)


        def test_pin_at_or_above_fix():
            assert REQ_PATH.exists(), f"requirements.txt missing at {{REQ_PATH}}"
            txt = REQ_PATH.read_text()
            for line in txt.splitlines():
                pkg, ver = _parse_pin(line)
                if pkg and pkg.lower() == PKG.lower():
                    if MIN:
                        assert _ver_key(ver) >= _ver_key(MIN), (
                            f"{{PKG}} pinned to {{ver}}, expected >= {{MIN}}"
                        )
                    return
            raise AssertionError(f"{{PKG}} not pinned in requirements.txt")
    ''').strip() + "\n"
    return (name, str(test_path), src)


def _author_http_header(change_id: str, plan: dict) -> tuple[str, str, str]:
    url = plan["url"]
    headers = plan["headers"]
    name = "test_security_headers_present"
    test_dir = TESTS_ROOT / change_id
    test_dir.mkdir(parents=True, exist_ok=True)
    test_path = test_dir / f"{name}.py"
    src = textwrap.dedent(f'''
        """Auto-generated by ai-protect: requests the live URL and asserts the
        security headers proposed by the remediation are now present."""
        import requests

        URL = {url!r}
        REQUIRED = {headers!r}


        def test_headers_present():
            r = requests.get(URL, timeout=10)
            r.raise_for_status()
            missing = [h for h in REQUIRED if h.lower() not in (k.lower() for k in r.headers)]
            assert not missing, f"missing headers: {{missing}}"
    ''').strip() + "\n"
    return (name, str(test_path), src)
