"""pip_bump — auto-fix pip_audit / grype / osv_scanner SUPPLY_CHAIN findings.

Strategy:
  - Gather every finding for this package across pip_audit / grype / osv_scanner
    (they overlap; we want the highest fixed version known across all sources)
  - Locate or create requirements.txt at manifest source_path
  - Pin the package to the lowest fixed version that clears the finding
  - Generate a unit test that asserts the pin is at-or-above the fix version

Confidence:
  - 0.9 when fix_versions exist
  - 0.4 when no fix_versions (finding asks for tracking, not auto-bump)
"""
from __future__ import annotations

from pathlib import Path

from ...core.findings import Category, Finding
from ..base import FileChange, Proposal, Remediator


class PipBumpRemediator(Remediator):
    name = "pip_bump"
    handles = {Category.SUPPLY_CHAIN}
    description = "Bump a Python dep to a fixed version in requirements.txt; generate a pin-version test."

    def can_fix(self, finding: Finding, manifest_raw: dict) -> bool:
        if finding.category != Category.SUPPLY_CHAIN:
            return False
        if finding.adapter not in ("pip_audit", "grype", "osv_scanner"):
            return False
        return bool((finding.evidence or {}).get("package"))

    def propose(self, finding: Finding, manifest_raw: dict) -> Proposal | None:
        ev = finding.evidence or {}
        pkg = ev.get("package")
        if not pkg:
            return None
        fixed_versions = ev.get("fixed_in") or ev.get("fix_versions") or []
        if isinstance(fixed_versions, str):
            fixed_versions = [fixed_versions]
        # Prefer the lowest fix version that clears the issue (least disruptive).
        fix = min(fixed_versions, key=_version_key) if fixed_versions else None

        source = Path(manifest_raw.get("source_path", "."))
        req_path = source / "requirements.txt"
        existing = req_path.read_text() if req_path.exists() else ""

        new_content, create = _patch_requirements(existing, pkg, fix)
        confidence = 0.9 if fix else 0.4

        if create:
            summary = f"Create {req_path} pinning {pkg}=={fix}"
        else:
            summary = f"Pin {pkg}=={fix} in {req_path}" if fix else f"Track {pkg} pin in {req_path}"

        return Proposal(
            summary=summary,
            confidence=confidence,
            rescan_adapter=finding.adapter,
            file_changes=[FileChange(
                path=str(req_path.resolve()),
                new_content=new_content,
                create=create,
            )],
            test_plan={
                "kind": "pin_version",
                "package": pkg,
                "min_version": fix,
                "requirements_path": str(req_path.resolve()),
            },
            notes=(
                f"Vuln {ev.get('vuln_id', 'CVE')}; installed {ev.get('installed') or ev.get('version')}. "
                f"Fixed in: {', '.join(fixed_versions) if fixed_versions else 'no fix published'}."
            ),
        )


def _version_key(v: str) -> tuple:
    """Crude version sort: tuple of ints + suffix as string. Good enough for fix-version ordering."""
    parts: list = []
    cur = ""
    for ch in v:
        if ch.isdigit():
            cur += ch
        else:
            if cur:
                parts.append(int(cur))
                cur = ""
            parts.append(ch)
    if cur:
        parts.append(int(cur))
    return tuple(parts)


def _patch_requirements(existing: str, pkg: str, fix: str | None) -> tuple[str, bool]:
    """Return (new content, created_new_file)."""
    create = not existing.strip()
    lines = existing.splitlines() if existing else []
    target_pin = f"{pkg}=={fix}" if fix else f"{pkg}  # tracking — no fix published"
    new_lines: list[str] = []
    replaced = False
    pkg_lower = pkg.lower()
    for ln in lines:
        stripped = ln.strip()
        # Match "<pkg>" or "<pkg>==..." or "<pkg>>=..." etc. case-insensitive.
        head = stripped.split("==", 1)[0].split(">=", 1)[0].split("<", 1)[0].split("~", 1)[0].strip()
        if head.lower() == pkg_lower and not replaced:
            new_lines.append(target_pin)
            replaced = True
        else:
            new_lines.append(ln)
    if not replaced:
        # Header for newly-created files.
        if create:
            new_lines = [
                "# requirements.txt — generated by ai-protect remediation engine.",
                "# Pins are the lowest fixed versions clearing pip_audit / grype / osv_scanner findings.",
                "# Review and tighten before committing.",
                "",
            ]
        new_lines.append(target_pin)
    out = "\n".join(new_lines)
    if not out.endswith("\n"):
        out += "\n"
    return out, create
